version: "3.8"
services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    environment:
      # Required: Your VPS Public IP or a Domain Name
      - WG_HOST=1.2.3.4 
      # Optional: Web UI Password (highly recommended)
      - PASSWORD=YourSecurePasswordHere
      # Optional: DNS for clients (e.g., Google or AdGuard)
      - WG_DEFAULT_DNS=8.8.8.8
    volumes:
      - wg_data:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

volumes:
  wg_data: